In [8]:
import pandas as pd

pd.set_option("display.min_rows", 30)

df = pd.read_csv('data/movies_list_02.csv')

# 数据清洗
# # 缺失值处理
# df.isnull() # 查看缺失值

# # 1。删除缺失值
# df = df.dropna() # 删除包含缺失值的行
# df = df.dropna(axis=1)

# 2。填充缺失值
df = df.fillna('*')
df
# df.ffill() # 填充缺失值，填充上一行数据
# df.bfill() # 填充缺失值，填充下一行数据

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,口号,描述,有效时长
0,蝙蝠俠 騎士殞落（一）：騎士殞落,2026,2026/08/25,"动画,动作,冒险,科幻",79,92,英語,比爾·芬格,鮑勃·凱恩,概覽,"Arkham Asylum has been destroyed, and all its ...",59
1,Avatar Aang: The Last Airbender,2026,2026/07/24,"动画,冒险,奇幻,动作",99,91,-,Tim Hedrick,勞倫·蒙哥馬利,The legacy reawakens.,"Avatar Aang, the world's last Airbender, learn...",79
2,奇幻變身大冒險,2026,2026/05/01,"冒险,动画,家庭,奇幻",102,89,英語,內森·格雷諾,Robert Snow,Transform your destiny.,林地小動物和大鳥突然互換了身體，只好彼此合作，共同面對一生最瘋狂的冒險。,82
3,Accidental Partners,2026,2026/03/12,"喜剧,爱情",110,88,西班牙語,Ihtzi Hurtado,Miguel García Moreno,概覽,Two women discover they were both scammed by t...,90
4,鬼滅之刃劇場版 無限城篇 第一章 猗窩座再襲,2025,2025/08/14,"动画,动作,奇幻",155,88,日語,外崎春雄,吾峠呼世晴,It's time to have some fun.,為了讓變成鬼的妹妹禰豆子變回人類，加入鬼殺隊的灶門炭治郎，一路上與不同的「柱」成為同伴，並肩...,135
5,夜巡毒梟,2026,2026/08/21,"犯罪,动作,惊悚",91,88,西班牙語,Chava Cartas,Bernardo Esquinca,概覽,兩位墨西哥員警不幸得罪一名殘忍的毒梟後，必須拼命撐過值勤的最後幾小時。這部犯罪劇情片改編自真...,71
6,月黑高飛,1994,1995/10/26,"剧情,犯罪",142,87,英語,法蘭·達拉本特,史提芬·京,Fear can hold you prisoner. Hope can set you f...,1947 年，一位年輕的波特蘭銀行家安迪·杜佛蘭（添·羅賓斯飾）被指控殺死其妻子與其情夫，分...,122
7,教父,1972,1980/01/24,"剧情,犯罪",175,87,英語,法蘭西斯·柯波拉,馬里奧·普佐,An offer you can't refuse.,電影描述西西里的柯里安大家族於美國掘起，辛苦掙扎奮鬥成為黑幫教父，最後引起權力鬥爭，甚至家族...,155
8,末日聖母號,2026,2026/03/19,"科幻,冒险",157,86,英語,菲力洛迪文,克里斯·米勒,Believe in the Hail Mary.,科學老師 Ryland Grace（賴恩高斯寧 飾）在一艘距離地球數光年遠的太空船上醒來，隨...,137
9,米高積遜,2026,2026/04/22,"音乐,剧情",128,86,英語,安東尼·福奎阿,約翰·洛根,Discover the making of a king.,《米高積遜》聚焦他的音樂成就，更深入描寫他舞台之外的人生軌跡：從幼年被發掘成為 Jackso...,108
10,年少心事,2024,2024/09/14,"剧情,爱情",99,86,荷蘭語,安東尼·沙特曼,*,概覽,在學期間，13 歲的 Elias 與來自布魯塞爾的 14 歲新鄰居 Alexander 成為...,79
11,教父續集,1974,1974/12/20,"剧情,犯罪",200,86,英語,法蘭西斯·柯波拉,馬里奧·普佐,The rise and fall of the Corleone empire.,柯裏安家族幼子米高（阿爾柏仙奴飾）自繼承大權後，續漸將勢力滲入各正當企業及政治圈中，企圖將黑...,180
12,十二怒漢,1957,1957/04/10,剧情,97,86,英語,雷金納德·羅斯,西德尼·盧梅特,It explodes like 12 sticks of dynamite!,本片所有場景幾乎都發生在一個小房間內，講述 11 名陪審團如何在另一名持反對意見的陪審團的説...,77
13,舒特拉的名單,1993,1994/03/17,"剧情,历史,战争",195,86,英語,史提芬·史匹堡,湯瑪斯·簡尼利,"Whoever saves one life, saves the world entire.",電影情節於 1939 年德國發起的猶太大移民開始。那時二戰剛剛打響，克拉科夫周圍的波蘭猶太人...,175
14,鏈鋸人 - 劇場版：蕾潔篇,2025,2025/09/25,"动画,动作,爱情,奇幻",100,86,日語,吉原達矢,瀨古浩司,"Lost Love, Flower, Chainsaw.",主角澱治曾是黑幫的惡魔獵人，試圖償還父母留下的債務。後來，他被黑幫背叛、殺害，就在瀕死之際，...,80
...,...,...,...,...,...,...,...,...,...,...,...,...
85,劇場版 五等分的新娘,2022,2022/10/06,"动画,喜剧,爱情",136,83,日語,神保昌登,大知慶一郎,概覽,講述為了讓「瀕臨留級」又「討厭學習」的美少女五姊妹通過學校考試畢業，主角風太郎以兼職家庭教師...,116
86,獻給我的前妻,2019,2019/11/08,"剧情,喜剧",94,83,西班牙語,Jorge Ulloa,Julio Pañi,概覽,這部電影講述了 21 歲的阿裏爾的故事：為籌錢挽回瀕臨破裂的戀情、與前女友重逢，他決定組建一...,74
87,大獨裁者,1940,1947/03/27,"喜剧,战争",125,83,英語,差利·卓別靈,*,Once again - the whole world laughs!,差利·卓別靈（Charles Chaplin）自導自演的第一部有聲片，此片拍攝於希特拉（Ad...,105
88,We All Loved Each Other So Much,1974,1974/12/21,"剧情,喜剧",125,83,意大利語,艾託尼·史寇拉,艾根諾爾·因克魯西,A many splendored thing.,Three partisans bound by a strong friendship r...,105
89,摩登時代,1936,1937/05/07,"喜剧,剧情,爱情",87,83,英語,差利·卓別靈,*,He stands alone as the greatest entertainer of...,《摩登時代》雖然是默片，但是實際上它包含聲音，比如收音機和電視機的聲音；卓別林以此來幫助 1...,67
90,邊境奇襲,2025,2025/02/28,"动作,冒险,惊悚",85,83,西班牙語,Chava Cartas,José Rubén Escalante Méndez,概覽,營救人質任務招來新敵人，格雷洛上尉和他率領的精銳士兵必須面對犯罪集團的伏擊。,65
91,莫負少年頭,1946,1946/12/20,"剧情,家庭,奇幻",131,83,英語,法蘭·基勃拉,阿爾伯特·莫里斯·哈克特,It's a wonderful laugh! It's a wonderful love!,美國 AFI 百大經典之一，喜愛經典電影的人必看佳片，一流的劇本，一流的演技。生命的價值何在...,111
92,制裁者：最後一擊,2026,2026/05/12,"动作,剧情,犯罪",51,83,英語,雷納爾多·馬庫斯·格林,傑瑞·康威,Hey Frank.,當法蘭克卡索尋求超越復仇的意義時，一股意想不到的力量將他拉回戰場。,31
93,Out of the Clear Blue Sky,2019,2019/12/24,"喜剧,剧情,音乐",112,83,西班牙語,Pepe Bojórquez,Alfredo Felix-Diaz,概覽,"Returning to Earth as an imitator, the legenda...",92
94,閃亮人生,2011,2012/09/06,"剧情,喜剧",113,83,法語,奧利維埃·納卡什,埃里克·託萊達諾,一對不平凡主僕 逆轉不一樣人生,出身法國貴族世家的菲臘（法司華古薩 飾），因一次跳傘意外而幾乎全身癱瘓，只剩下情緖意識和思考...,93
95,紅樓金粉,1950,1950/08/10,剧情,110,83,英語,比利·懷特,查爾斯·威廉·布萊克特,A Hollywood Story: Sensational...Daring...Unfo...,比利·懷德（Billy Wilder）執導 1950 年代美國黑色電影經典之作，獲第 52 ...,90
96,捕風追影,2025,2025/09/11,"动作,犯罪,剧情,惊悚",142,83,漢語,楊子,*,He's training a new generation of law enforcer...,一夥天才盜匪劫走數億資產，卻憑藉超強反偵察能力全身而退，戲耍警方“天眼”系統。一籌莫展之際，...,122
97,狂沙十萬里,1968,1969/09/25,"剧情,西部",166,83,意大利語,賽爾喬·萊昂內,塞爾吉奧·多納蒂,There were three men in her life. One to take ...,義大利西部片宗師李歐尼（Sergio Leone）的傳世經典之作，繼與克林伊斯威特合作「鏢客...,146
98,現代啟示錄,1979,1980/03/27,"剧情,战争",153,83,英語,法蘭西斯·柯波拉,約瑟夫·康拉德,This is the end...,1968 年，特種部隊上尉班傑明·韋勒（Benjamin L.Willard）奉命前往越南「...,133
99,新世紀福音戰士劇場版：Air／真心為你,1997,2026/10/01,"动画,科幻,剧情,奇幻,动作",87,83,日語,庵野秀明,鶴卷和哉,The fate of destruction is also the joy of reb...,本作是由 TV 版第 25 話與最終話的重新製作所構成的兩話內容。第 25 話〈Air〉：在...,67

In [11]:
# 重复值
df.duplicated() # 所有列都重复
df.duplicated(subset=['语言'])

# 删除重复值
df.drop_duplicates(subset=['语言'],keep='last') #keep = 'last' 删除重复值，保留最后一个; keep = 'first' 删除重复值，保留第一个

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,口号,描述,有效时长
10,年少心事,2024,2024/09/14,"剧情,爱情",99,86,荷蘭語,安東尼·沙特曼,*,概覽,在學期間，13 歲的 Elias 與來自布魯塞爾的 14 歲新鄰居 Alexander 成為...,79
19,漂洋過海愛上你,1995,1995/10/20,"喜剧,剧情,爱情",190,85,印地語,Aditya Chopra,*,"Come… fall In love, all over again…",當拉傑（沙魯克罕飾）與希姆蘭（卡約兒飾）首次在歐洲的鐵路假日行相遇時，並未徹底一見鍾情。但是...,170
43,A Dog's Will,2000,2000/09/15,"喜剧,剧情,奇幻,爱情",104,84,葡萄牙語,蓋爾·阿賴斯,Ariano Suassuna,Lying with faith is not always a sin.,The lively João Grilo and the sly Chicó are po...,84
73,同級生,2016,2016/02/20,"爱情,动画",61,83,-,中村章子,中村明日美子,"Sincerely, Slowly, Falling in Love.",關於青春期中的少年們的純情故事。高中入學測驗獲得滿分成績的秀才佐條利人，以及遭受女生歡迎異性...,41
82,帶來靈魂：防彈少年團演唱會電影,2019,2019/08/07,"音乐,纪录",105,83,韓語,Park Jun-soo,*,"Forever, we are young.",據媒體報道防彈少年團 第三部演唱會電影《Bring the Soul：The Movie》確...,85
93,Out of the Clear Blue Sky,2019,2019/12/24,"喜剧,剧情,音乐",112,83,西班牙語,Pepe Bojórquez,Alfredo Felix-Diaz,概覽,"Returning to Earth as an imitator, the legenda...",92
94,閃亮人生,2011,2012/09/06,"剧情,喜剧",113,83,法語,奧利維埃·納卡什,埃里克·託萊達諾,一對不平凡主僕 逆轉不一樣人生,出身法國貴族世家的菲臘（法司華古薩 飾），因一次跳傘意外而幾乎全身癱瘓，只剩下情緖意識和思考...,93
96,捕風追影,2025,2025/09/11,"动作,犯罪,剧情,惊悚",142,83,漢語,楊子,*,He's training a new generation of law enforcer...,一夥天才盜匪劫走數億資產，卻憑藉超強反偵察能力全身而退，戲耍警方“天眼”系統。一籌莫展之際，...,122
97,狂沙十萬里,1968,1969/09/25,"剧情,西部",166,83,意大利語,賽爾喬·萊昂內,塞爾吉奧·多納蒂,There were three men in her life. One to take ...,義大利西部片宗師李歐尼（Sergio Leone）的傳世經典之作，繼與克林伊斯威特合作「鏢客...,146
98,現代啟示錄,1979,1980/03/27,"剧情,战争",153,83,英語,法蘭西斯·柯波拉,約瑟夫·康拉德,This is the end...,1968 年，特種部隊上尉班傑明·韋勒（Benjamin L.Willard）奉命前往越南「...,133
99,新世紀福音戰士劇場版：Air／真心為你,1997,2026/10/01,"动画,科幻,剧情,奇幻,动作",87,83,日語,庵野秀明,鶴卷和哉,The fate of destruction is also the joy of reb...,本作是由 TV 版第 25 話與最終話的重新製作所構成的兩話內容。第 25 話〈Air〉：在...,67

In [16]:
# 异常值的处理
# 查看异常数据
df[df['评分'] > 100]

# 删除异常数据
df.drop(df[df['评分'] > 100].index)

# 修复异常值
df['评分'] = df['评分'].abs() # 绝对值

In [17]:
# 数据格式处理
df['上映时间'] = df['上映时间'].str.replace('/','-')
df

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,口号,描述,有效时长
0,蝙蝠俠 騎士殞落（一）：騎士殞落,2026,2026-08-25,"动画,动作,冒险,科幻",79,92,英語,比爾·芬格,鮑勃·凱恩,概覽,"Arkham Asylum has been destroyed, and all its ...",59
1,Avatar Aang: The Last Airbender,2026,2026-07-24,"动画,冒险,奇幻,动作",99,91,-,Tim Hedrick,勞倫·蒙哥馬利,The legacy reawakens.,"Avatar Aang, the world's last Airbender, learn...",79
2,奇幻變身大冒險,2026,2026-05-01,"冒险,动画,家庭,奇幻",102,89,英語,內森·格雷諾,Robert Snow,Transform your destiny.,林地小動物和大鳥突然互換了身體，只好彼此合作，共同面對一生最瘋狂的冒險。,82
3,Accidental Partners,2026,2026-03-12,"喜剧,爱情",110,88,西班牙語,Ihtzi Hurtado,Miguel García Moreno,概覽,Two women discover they were both scammed by t...,90
4,鬼滅之刃劇場版 無限城篇 第一章 猗窩座再襲,2025,2025-08-14,"动画,动作,奇幻",155,88,日語,外崎春雄,吾峠呼世晴,It's time to have some fun.,為了讓變成鬼的妹妹禰豆子變回人類，加入鬼殺隊的灶門炭治郎，一路上與不同的「柱」成為同伴，並肩...,135
5,夜巡毒梟,2026,2026-08-21,"犯罪,动作,惊悚",91,88,西班牙語,Chava Cartas,Bernardo Esquinca,概覽,兩位墨西哥員警不幸得罪一名殘忍的毒梟後，必須拼命撐過值勤的最後幾小時。這部犯罪劇情片改編自真...,71
6,月黑高飛,1994,1995-10-26,"剧情,犯罪",142,87,英語,法蘭·達拉本特,史提芬·京,Fear can hold you prisoner. Hope can set you f...,1947 年，一位年輕的波特蘭銀行家安迪·杜佛蘭（添·羅賓斯飾）被指控殺死其妻子與其情夫，分...,122
7,教父,1972,1980-01-24,"剧情,犯罪",175,87,英語,法蘭西斯·柯波拉,馬里奧·普佐,An offer you can't refuse.,電影描述西西里的柯里安大家族於美國掘起，辛苦掙扎奮鬥成為黑幫教父，最後引起權力鬥爭，甚至家族...,155
8,末日聖母號,2026,2026-03-19,"科幻,冒险",157,86,英語,菲力洛迪文,克里斯·米勒,Believe in the Hail Mary.,科學老師 Ryland Grace（賴恩高斯寧 飾）在一艘距離地球數光年遠的太空船上醒來，隨...,137
9,米高積遜,2026,2026-04-22,"音乐,剧情",128,86,英語,安東尼·福奎阿,約翰·洛根,Discover the making of a king.,《米高積遜》聚焦他的音樂成就，更深入描寫他舞台之外的人生軌跡：從幼年被發掘成為 Jackso...,108
10,年少心事,2024,2024-09-14,"剧情,爱情",99,86,荷蘭語,安東尼·沙特曼,*,概覽,在學期間，13 歲的 Elias 與來自布魯塞爾的 14 歲新鄰居 Alexander 成為...,79
11,教父續集,1974,1974-12-20,"剧情,犯罪",200,86,英語,法蘭西斯·柯波拉,馬里奧·普佐,The rise and fall of the Corleone empire.,柯裏安家族幼子米高（阿爾柏仙奴飾）自繼承大權後，續漸將勢力滲入各正當企業及政治圈中，企圖將黑...,180
12,十二怒漢,1957,1957-04-10,剧情,97,86,英語,雷金納德·羅斯,西德尼·盧梅特,It explodes like 12 sticks of dynamite!,本片所有場景幾乎都發生在一個小房間內，講述 11 名陪審團如何在另一名持反對意見的陪審團的説...,77
13,舒特拉的名單,1993,1994-03-17,"剧情,历史,战争",195,86,英語,史提芬·史匹堡,湯瑪斯·簡尼利,"Whoever saves one life, saves the world entire.",電影情節於 1939 年德國發起的猶太大移民開始。那時二戰剛剛打響，克拉科夫周圍的波蘭猶太人...,175
14,鏈鋸人 - 劇場版：蕾潔篇,2025,2025-09-25,"动画,动作,爱情,奇幻",100,86,日語,吉原達矢,瀨古浩司,"Lost Love, Flower, Chainsaw.",主角澱治曾是黑幫的惡魔獵人，試圖償還父母留下的債務。後來，他被黑幫背叛、殺害，就在瀕死之際，...,80
...,...,...,...,...,...,...,...,...,...,...,...,...
85,劇場版 五等分的新娘,2022,2022-10-06,"动画,喜剧,爱情",136,83,日語,神保昌登,大知慶一郎,概覽,講述為了讓「瀕臨留級」又「討厭學習」的美少女五姊妹通過學校考試畢業，主角風太郎以兼職家庭教師...,116
86,獻給我的前妻,2019,2019-11-08,"剧情,喜剧",94,83,西班牙語,Jorge Ulloa,Julio Pañi,概覽,這部電影講述了 21 歲的阿裏爾的故事：為籌錢挽回瀕臨破裂的戀情、與前女友重逢，他決定組建一...,74
87,大獨裁者,1940,1947-03-27,"喜剧,战争",125,83,英語,差利·卓別靈,*,Once again - the whole world laughs!,差利·卓別靈（Charles Chaplin）自導自演的第一部有聲片，此片拍攝於希特拉（Ad...,105
88,We All Loved Each Other So Much,1974,1974-12-21,"剧情,喜剧",125,83,意大利語,艾託尼·史寇拉,艾根諾爾·因克魯西,A many splendored thing.,Three partisans bound by a strong friendship r...,105
89,摩登時代,1936,1937-05-07,"喜剧,剧情,爱情",87,83,英語,差利·卓別靈,*,He stands alone as the greatest entertainer of...,《摩登時代》雖然是默片，但是實際上它包含聲音，比如收音機和電視機的聲音；卓別林以此來幫助 1...,67
90,邊境奇襲,2025,2025-02-28,"动作,冒险,惊悚",85,83,西班牙語,Chava Cartas,José Rubén Escalante Méndez,概覽,營救人質任務招來新敵人，格雷洛上尉和他率領的精銳士兵必須面對犯罪集團的伏擊。,65
91,莫負少年頭,1946,1946-12-20,"剧情,家庭,奇幻",131,83,英語,法蘭·基勃拉,阿爾伯特·莫里斯·哈克特,It's a wonderful laugh! It's a wonderful love!,美國 AFI 百大經典之一，喜愛經典電影的人必看佳片，一流的劇本，一流的演技。生命的價值何在...,111
92,制裁者：最後一擊,2026,2026-05-12,"动作,剧情,犯罪",51,83,英語,雷納爾多·馬庫斯·格林,傑瑞·康威,Hey Frank.,當法蘭克卡索尋求超越復仇的意義時，一股意想不到的力量將他拉回戰場。,31
93,Out of the Clear Blue Sky,2019,2019-12-24,"喜剧,剧情,音乐",112,83,西班牙語,Pepe Bojórquez,Alfredo Felix-Diaz,概覽,"Returning to Earth as an imitator, the legenda...",92
94,閃亮人生,2011,2012-09-06,"剧情,喜剧",113,83,法語,奧利維埃·納卡什,埃里克·託萊達諾,一對不平凡主僕 逆轉不一樣人生,出身法國貴族世家的菲臘（法司華古薩 飾），因一次跳傘意外而幾乎全身癱瘓，只剩下情緖意識和思考...,93
95,紅樓金粉,1950,1950-08-10,剧情,110,83,英語,比利·懷特,查爾斯·威廉·布萊克特,A Hollywood Story: Sensational...Daring...Unfo...,比利·懷德（Billy Wilder）執導 1950 年代美國黑色電影經典之作，獲第 52 ...,90
96,捕風追影,2025,2025-09-11,"动作,犯罪,剧情,惊悚",142,83,漢語,楊子,*,He's training a new generation of law enforcer...,一夥天才盜匪劫走數億資產，卻憑藉超強反偵察能力全身而退，戲耍警方“天眼”系統。一籌莫展之際，...,122
97,狂沙十萬里,1968,1969-09-25,"剧情,西部",166,83,意大利語,賽爾喬·萊昂內,塞爾吉奧·多納蒂,There were three men in her life. One to take ...,義大利西部片宗師李歐尼（Sergio Leone）的傳世經典之作，繼與克林伊斯威特合作「鏢客...,146
98,現代啟示錄,1979,1980-03-27,"剧情,战争",153,83,英語,法蘭西斯·柯波拉,約瑟夫·康拉德,This is the end...,1968 年，特種部隊上尉班傑明·韋勒（Benjamin L.Willard）奉命前往越南「...,133
99,新世紀福音戰士劇場版：Air／真心為你,1997,2026-10-01,"动画,科幻,剧情,奇幻,动作",87,83,日語,庵野秀明,鶴卷和哉,The fate of destruction is also the joy of reb...,本作是由 TV 版第 25 話與最終話的重新製作所構成的兩話內容。第 25 話〈Air〉：在...,67